services:
  app:
    image: node:20.2.0
    command: sh -c "./startup.sh"
    ports:
      - 8080:8080
    working_dir:  /app
    volumes:
      - ./:/app
      - /app/node_modules/
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3
    restart: always
    volumes: 
      - e-commerce-api-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  e-commerce-api-data:
    driver: local
      
